Add some tests on Repository
EsupPortail/esup-stage pull request #11
Opened 2021-01-20 13:10 UTC by shiipou

Test all repository from EdutiantRepository To OffreRepository.

2021-01-21 11:29 UTC, shiipou commented
Encore quelques soucis au niveau de la Classe `Offre` nécessaire dans certaines classes de tests.

2021-01-22 11:04 UTC, shiipou commented
I have some error I need to fix :

- [ ] FAP_QualificationSimplifieeRepositoryTest > `Index 0 out of bounds for length (FAP_QualificationSimplifieeRepositoryTest.java:174)`
- [ ] EtudiantRepositoryTest > findEtudiantByIdentEtudiantAndCodeUniversite `We should have found our Student ==> expected: <true> but was: <false>`
- [ ] EtudiantRepositoryTest > findEtudiantsByNomContainsOrPrenomContains > `We should have found our Student ==> expected: <true> but was: <false>`
- [ ] FichierRepositoryTest > `Fichier.CentreGestion size match ==> expected: <1> but was: <0>`

2021-02-04 09:33 UTC, JoshuaBaubry requested changes
Pour moi c'est bon à part pour les choses que j'ai mises

2021-02-04 09:33 UTC, JoshuaBaubry commented on .env
> +POSTGRES_PASSWORD="esupstage"
pourquoi il y a ce fichier ?

2021-02-04 09:33 UTC, JoshuaBaubry commented on .env.test
> +POSTGRES_PASSWORD="esupstage"
idem

2021-02-04 09:33 UTC, JoshuaBaubry commented on build.gradle
> +}
peut être retiré du coup

2021-02-04 09:33 UTC, JoshuaBaubry commented on gradle/wrapper/gradle-wrapper.properties
> +zipStorePath=wrapper/dists
idem

2021-02-04 09:33 UTC, JoshuaBaubry commented on gradlew
> +exec "$JAVACMD" "$@"
idem

2021-02-04 09:33 UTC, JoshuaBaubry commented on gradlew.bat
> +:omega
idem

2021-02-04 09:33 UTC, JoshuaBaubry commented on settings.gradle
> +rootProject.name = 'esupstage'
idem

2021-02-04 09:33 UTC, JoshuaBaubry commented on src/main/resources/application.yml
> +...
il y a un soucis d'encodage ici ça remplace tout le fichier

2021-02-04 13:12 UTC, shiipou commented on .env
> +POSTGRES_PASSWORD="esupstage"
Ah il permettait de configurer mon postgres de test. J'ai du le remettre avec les rebases.

2021-02-04 13:12 UTC, shiipou commented on .env.test
> +POSTGRES_PASSWORD="esupstage"
https://github.com/EsupPortail/esup-stage/pull/11#discussion_r570211367

2021-02-04 13:12 UTC, shiipou commented on build.gradle
> +}
Oui

2021-02-04 13:13 UTC, shiipou commented on gradle/wrapper/gradle-wrapper.properties
> +zipStorePath=wrapper/dists
https://github.com/EsupPortail/esup-stage/pull/11#discussion_r570211595

2021-02-04 13:13 UTC, shiipou commented on gradlew
> +exec "$JAVACMD" "$@"
https://github.com/EsupPortail/esup-stage/pull/11#discussion_r570211595

2021-02-04 13:13 UTC, shiipou commented on gradlew.bat
> +:omega
https://github.com/EsupPortail/esup-stage/pull/11#discussion_r570211595

2021-02-04 13:13 UTC, shiipou commented on settings.gradle
> +rootProject.name = 'esupstage'
https://github.com/EsupPortail/esup-stage/pull/11#discussion_r570211595

2021-02-04 13:47 UTC, shiipou commented on src/main/resources/application.yml
> +...
Pourtant j'ai utilisé l'interface Web de Git pour le récupérer.

2021-02-05 11:27 UTC, JoshuaBaubry commented on src/main/resources/application.yml
> +...
oui c'est pas la première fois qu'on a un soucis avec ce fichier

2021-02-10 12:26 UTC, shiipou commented on src/main/resources/application.yml
> +...
J'arrive pas à résoudre ce soucis, si t'as des conseils je suis preneur.

2021-02-10 13:40 UTC, JoshuaBaubry commented on src/main/resources/application.yml
> +...
On avait galéré avec Vianney sans vraiment trouver de solutions, y'a bien une commande git , essaye git config --global core.autocrlf true

2021-04-01 13:01 UTC, closed without merging